set guioptions+=k
set guioptions-=T

set expandtab
set shiftwidth=2
set tabstop=2
set wildignorecase

let maplocalleader = "\<Space>"

if !exists('g:vimrc')
  let g:vimrc = $MYVIMRC
endif
if !exists('g:vimplugins')
  let g:vimplugins = g:vimrc
endif

if executable('rg')
  let $FZF_DEFAULT_COMMAND = 'rg --files --hidden'
  let g:ackprg = 'rg --vimgrep'
endif

let g:tt_use_defaults = 1
let g:tt_taskfile = '~/Documents/tasks.md'

if has('win32')
  let g:gtfo#terminals = { 'win': 'powershell -NoLogo -NoExit -Command' }
endif

let g:ale_linters = {'clojure': ['clj-kondo']}

let g:zoxide_hook = 'pwd'

try
  unmap <C-f>
  unmap! <C-f>
catch
  " oh well
endtry

nnoremap <C-@> :Files<CR>
nnoremap <C-Space> :Files<CR>
nnoremap gb :BufExplorer<CR>
nnoremap gc :Lzi<CR>
nnoremap gs <plug>(GrepperOperator)
xnoremap gs <plug>(GrepperOperator)
nnoremap gx :Dirvish %:p:h<CR>
nnoremap g. :execute 'edit' g:vimrc<CR>
nnoremap g/ :execute 'edit' g:vimplugins<CR>
nnoremap [q :cprevious<CR>
nnoremap ]q :cnext<CR>
autocmd BufReadPost * if expand('%') ==# g:vimrc | nnoremap <buffer> <CR> :update <Bar> source %<CR> | endif
nnoremap <C-^> :A<CR>

xnoremap / y/<C-R>"<CR>

nnoremap <silent> <CR> :wall <Bar> :TestFile<CR>
autocmd CmdwinEnter * nnoremap <buffer> <CR> <CR>
autocmd BufReadPost * if &buftype ==# 'quickfix' | nnoremap <buffer> <CR> <CR> | endif

nnoremap <LocalLeader>tf :silent! wa <bar> :TestFile<CR>
nnoremap <LocalLeader>ts :silent! wa <bar> :TestNearest<CR>

set foldlevel=99
set foldmethod=indent
nnoremap <Leader>1 :set foldlevel=1<cr>
nnoremap <Leader>2 :set foldlevel=2<cr>
nnoremap <Leader>3 :set foldlevel=3<cr>
nnoremap <Leader>4 :set foldlevel=4<cr>
nnoremap <Leader>0 :set foldlevel=99<cr>

nnoremap <Leader>d "=strftime("%a, %d %b %Y %H:%M:%S %z")<CR>P

set clipboard=unnamed,unnamedplus

autocmd FileType html nnoremap <buffer> gob :call system('xdg-open ' . expand('%:S'))<cr>

try
  colorscheme gruvbox
catch /^Vim\%((\a\+)\)\=:E185/
  " oh well
endtry

if exists(":VimRSetFontAndSize")
  VimRSetFontAndSize "IBM Plex Mono", 12
else
  try
    set guifont=IBM\ Plex\ Mono:h11
  catch /^E596/
    "oh well
  endtry
endif
